services:
  vllm-qwen_vl:
    container_name: vllm-qwen_vl
    build:
        context: ../
        dockerfile: docker/Dockerfile
    image: ding/qwen_vl:v1
    privileged: true
    ipc: host
    shm_size: "80gb"
    working_dir: /app
    entrypoint: []
    environment:
      - MTHREADS_VISIBLE_DEVICES=all
    volumes:
      - /data/models:/models
    command:
      - /bin/bash
      - -c
      - |        
        python app.py || tail -f /dev/null
    ports:
      - "8020:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"