services:
  vllm-qwen_vl:
    container_name: vllm-qwen_vl
    image: registry.mthreads.com/mcconline/vllm-musa-qy2-py310:v0.7.3
    privileged: true
    ipc: host
    shm_size: "80gb"
    working_dir: /app
    entrypoint: []
    environment:
      - MTHREADS_VISIBLE_DEVICES=all
    volumes:
      - /data/models:/models
    command:
      - /bin/bash
      - -c
      - |        
        python app.py
    ports:
      - "8020:8000"
    networks:
      - ragflow
